version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverlet.collector
    versions:
    - "> 1.3.0, < 1.4"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.6.1, < 16.7"
  - dependency-name: xunit
    versions:
    - "> 2.4.0, < 2.5"
  - dependency-name: xunit.runner.visualstudio
    versions:
    - "> 2.4.0, < 2.5"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.2
